services:
  front:
    build: 
      context: .
      dockerfile: front.Dockerfile
    container_name: front
    ports:
      - "5173:5173"
    volumes:
      - front_data:/usr/src/app/node_modules
      - ./frontend:/frontend
    depends_on:
      - back

  back:
    build:
      context: .
      dockerfile: back.Dockerfile
    container_name: back
    ports:
      - "4000:4000"
    volumes:
      - back_data:/usr/src/app/node_modules
      - ./backend:/backend
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@banco:5432/${POSTGRES_DB}
    depends_on:
      - banco



  banco:
    image: postgres:16.2
    container_name: postgres_db
    ports:
      - "5432:5432"
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always 



  pgadmin:
    image: dpage/pgadmin4:8.8
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    # restart: always
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      -  banco

volumes:
  postgres_data:
  pgadmin_data:
  front_data:
  back_data: