site_name: Mapa da Violência
repo_name: "T2G1-IA-Gloria"
repo_url: "https://github.com/ResidenciaTICBrisa/T2G1-IA-Gloria"

theme:
  name: material
  language: "pt"
  favicon: img/logo.png
  features:
    - navigation.tabs
  logo: img/favicon.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: purple
      toggle:
        icon: material/brightness-7
        name: Alterar para o modo escuro
      accent: white

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      toggle:
        icon: material/brightness-4
        name: Alterar para o modo claro

nav:
  - Início: index.md
  - Atas:
    - Ata da Reunião 01 - 03/03: atas/03-03-2024.md
    - Ata da Reunião 02 - 14/03: atas/14-03-2024.md
    - Ata da Reunião 02 - 22/03: atas/22-03-2024.md
  - Modelagem Banco de Dados: modelagem_banco/modelo_relacional.md
  - Figma: 
    - Versão 1: prototipos_figma/versao1.md
    - Versão 2: prototipos_figma/versao2.md
    - Versão 3: prototipos_figma/versao3.md
  - Elicitação de Requisitos: requisitos/requisitos.md
  - Sprint Backlog:
      - Sprints: sprints/sprints.md
      - Roadmap: sprints/roadmap.md
  - Templates:
    - Template Atas: templatess/atas.md
    - Template Issues: templatess/issues.md
  - Diagramas:
    - Fluxograma da Interface: diagramas/fluxograma_interface.md
    - Arquitetura do Projeto: diagramas/arquitetura.md
