site_name: Mapa da Violência
repo_name: "T2G1-IA-Gloria"
repo_url: "https://github.com/ResidenciaTICBrisa/T2G1-IA-Gloria"

theme:
  name: material
  language: "pt"
  palette:
    primary: purple
    accent: yellow
  features:
    - navigation.tabs 

nav:
  - Início: index.md
  - Atas:
    - Ata da Reunião 01 - 03/03: atas/03-03-2024.md
    - Ata da Reunião 02 - 14/03: atas/14-03-2024.md
    - Ata da Reunião 02 - 22/03: atas/22-03-2024.md
  - Modelagem Banco de Dados: modelagem_banco/modelo_relacional.md
  - Figma: 
    - Versão 1: prototipos_figma/versao1.md
    - Versão 2: prototipos_figma/versao2.md
    - Versão 3: prototipos_figma/versao3.md
  - Elicitação de Requisitos: requisitos/requisitos.md
  - Sprint Backlog: sprints/sprints.md
  - Templates:
    - Template Atas: templatess/atas.md
    - Template Issues: templatess/issues.md
  - Diagramas:
    - Fluxograma da Interface: diagramas/fluxograma_interface.md
    - Arquitetura do Projeto: diagramas/arquitetura.md
