site_name: Mapa da Violência
repo_name: "T2G1-IA-Gloria"
repo_url: "https://github.com/ResidenciaTICBrisa/T2G1-IA-Gloria"

theme:
  name: material
  language: "pt"
  palette:
    primary: purple
    accent: yellow
  features:
    -navigation.tabs 

nav:
  - Início: index.md
  - Atas:
    - Ata 1: atas/03-03-2024.md
    - Ata 2: atas/14-03-2024.md
    - Ata 3: atas/22-03-2024.md
  - Modelagem Banco de Dados:
    - Modelo 1: modelagem_banco/modelo_relacional.md
